// Démonstration exécutable du nettoyeur de provenance porté depuis le `.zip` (branche `Exemple`).
//
// Ce n'est pas un test : c'est la sortie « avant / après » sur des échantillons construits à la
// main, pour répondre à la question « est-ce que les fonctionnalités du zip sont vraiment dans
// l'appli ? » avec des octets, pas avec une promesse.
//
//   kotlinc app/src/main/java/com/souxch/watermarkremover/cleaner/NativeWatermarkCleaner.kt \
//          app/src/main/java/com/souxch/watermarkremover/cleaner/TextUnicodeCleaner.kt \
//          verify/src/DemoCleaner.kt -include-runtime -d demo.jar
//   java -Dstdout.encoding=UTF-8 -jar demo.jar
//
// Le cas n° 5 est le plus important : un média ordinaire, sans marque de provenance, ressort
// **identique**. C'est voulu — le nettoyeur ne touche pas aux pixels, il ne peut donc pas faire
// disparaître un filigrane visible (logo ou texte incrusté). Voir AUDIT-ZIP.md.

package com.souxch.watermarkremover.verify

import com.souxch.watermarkremover.cleaner.NativeWatermarkCleaner
import java.io.ByteArrayOutputStream
import java.util.zip.CRC32
import java.util.zip.ZipEntry
import java.util.zip.ZipOutputStream

private fun report(label: String, name: String, mime: String, input: ByteArray) {
    val out = NativeWatermarkCleaner.clean(name, mime, input)
    val hex = out.bytes.joinToString("") { "%02x".format(it) }
    println("── $label")
    println("   type détecté    : ${out.report.kind}  ($name / $mime)")
    println("   octets          : ${out.report.bytesIn} → ${out.report.bytesOut}   modifié=${out.report.changed}")
    println("   « c2pa » encore là ? ${input.toString(Charsets.ISO_8859_1).contains("c2pa", true)} → " +
        "${out.bytes.toString(Charsets.ISO_8859_1).contains("c2pa", true)}")
    out.report.actions.forEach { println("   • action        : $it") }
    out.report.warnings.take(2).forEach { println("   ⚠ avertissement  : $it") }
    out.report.residualMarkers.take(3).forEach { println("   ⚠ résidu        : $it") }
    if (hex.length < 120) println("   sortie (hex)    : $hex")
    println()
}

/** PNG minimal (1×1) + un chunk texte de provenance, comme en ajoutent les générateurs d'images. */
private fun pngWithProvenanceChunk(): ByteArray {
    val png = ByteArrayOutputStream()
    png.write(byteArrayOf(0x89.toByte(), 'P'.code.toByte(), 'N'.code.toByte(), 'G'.code.toByte(), 0x0D, 0x0A, 0x1A, 0x0A))
    fun chunk(type: String, data: ByteArray) {
        val crc = CRC32()
        val payload = type.toByteArray() + data
        crc.update(payload)
        png.write(byteArrayOf(
            ((data.size ushr 24) and 0xFF).toByte(), ((data.size ushr 16) and 0xFF).toByte(),
            ((data.size ushr 8) and 0xFF).toByte(), (data.size and 0xFF).toByte(),
        ))
        png.write(payload)
        val c = crc.value
        png.write(byteArrayOf(
            ((c ushr 24) and 0xFF).toByte(), ((c ushr 16) and 0xFF).toByte(),
            ((c ushr 8) and 0xFF).toByte(), (c and 0xFF).toByte(),
        ))
    }
    chunk("IHDR", byteArrayOf(0, 0, 0, 1, 0, 0, 0, 1, 8, 0, 0, 0, 0))
    chunk("tEXt", ("c2pa" + "\u0000" + "generated by an AI model").toByteArray(Charsets.ISO_8859_1))
    chunk("IDAT", byteArrayOf(0x78, 0x9C.toByte(), 0x62, 0x00, 0x01, 0x00, 0x00, 0x05, 0x00, 0x01))
    chunk("IEND", ByteArray(0))
    return png.toByteArray()
}

private fun box(out: ByteArrayOutputStream, type: String, payload: ByteArray) {
    val size = 8 + payload.size
    out.write(byteArrayOf(
        ((size ushr 24) and 0xFF).toByte(), ((size ushr 16) and 0xFF).toByte(),
        ((size ushr 8) and 0xFF).toByte(), (size and 0xFF).toByte(),
    ))
    out.write(type.toByteArray(Charsets.ISO_8859_1))
    out.write(payload)
}

/** MP4 minimal : en-tête `ftyp`, une boîte `uuid` C2PA (ce que portent les vidéos « IA »), un `mdat`. */
private fun mp4WithC2paUuid(): ByteArray {
    val out = ByteArrayOutputStream()
    box(out, "ftyp", "isom\u0000\u0000\u0002\u0000isomiso2mp41".toByteArray(Charsets.ISO_8859_1))
    val c2paUuid = byteArrayOf(
        0x00, 0x00, 0x00, 0x00,
        0xD8.toByte(), 0xFE.toByte(), 0xC3.toByte(), 0xD6.toByte(), 0x1B, 0x0E, 0x48, 0x3C,
        0xA1.toByte(), 0xD0.toByte(), 0xB0.toByte(), 0xD0.toByte(), 0xD0.toByte(), 0xD0.toByte(), 0xD0.toByte(), 0xD0.toByte(),
        'c'.code.toByte(), '2'.code.toByte(), 'p'.code.toByte(), 'a'.code.toByte(),
    )
    box(out, "uuid", c2paUuid)
    box(out, "mdat", ByteArray(64) { 0x11 })
    return out.toByteArray()
}

/** MP4 minimal **sans** aucune marque : le cas « toujours le même résultat ». */
private fun plainMp4(): ByteArray {
    val out = ByteArrayOutputStream()
    box(out, "ftyp", "isom\u0000\u0000\u0002\u0000isomiso2mp41".toByteArray(Charsets.ISO_8859_1))
    box(out, "mdat", ByteArray(64) { 0x33 })
    return out.toByteArray()
}

private fun docxWithProvenanceProps(): ByteArray {
    val out = ByteArrayOutputStream()
    ZipOutputStream(out).use { zip ->
        zip.putNextEntry(ZipEntry("[Content_Types].xml"))
        zip.write("<Types/>".toByteArray())
        zip.closeEntry()
        zip.putNextEntry(ZipEntry("word/document.xml"))
        zip.write("<w:document><w:body>texte visible</w:body></w:document>".toByteArray())
        zip.closeEntry()
        zip.putNextEntry(ZipEntry("docProps/core.xml"))
        zip.write("<cp:coreProperties><dc:creator>c2pa generator</dc:creator>".toByteArray())
        zip.closeEntry()
    }
    return out.toByteArray()
}

fun main() {
    println("=== Nettoyeur de provenance porté depuis le .zip — sources de l'APK, exécutées ici ===\n")

    report(
        "1. Texte avec caractères Unicode invisibles (le « Layer A » du .zip)",
        "notes.txt", "text/plain",
        "Bonjour\u200B le\u00A0monde\uFEFF avec\u2060 des\u200D espions".toByteArray(),
    )
    report("2. PNG avec un chunk de provenance (C2PA / EXIF texte)", "photo.png", "image/png", pngWithProvenanceChunk())
    report("3. MP4 avec la boîte uuid C2PA des vidéos générées par IA", "clip.mp4", "video/mp4", mp4WithC2paUuid())
    report(
        "4. DOCX (archive ZIP) avec docProps de provenance",
        "rapport.docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        docxWithProvenanceProps(),
    )
    report("5. CONTRÔLE : MP4 ordinaire SANS marque de provenance (le cas « rien ne change »)", "ma_video.mp4", "video/mp4", plainMp4())
}
